# Configuración para entorno de producción
spring:
  # Configuración de base de datos para producción
  datasource:
    url: jdbc:${DB_TYPE:mysql}://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # Configuración JPA para producción
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    open-in-view: false
  
  # Configuración de Flyway para producción
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  
  # Configuración de mail para producción
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${SMTP_HOST}

# Configuración del servidor para producción
server:
  port: ${PORT:8080}

# Configuración de la aplicación para producción
app:
  host: ${HOST:0.0.0.0}
  environment: production
  repository:
    type: ${APP_REPOSITORY_TYPE:jpa}
    test-type: ${TEST_REPOSITORY_TYPE:mock}

# Configuración de email para producción
email:
  smtp-host: ${SMTP_HOST}
  smtp-port: ${SMTP_PORT:587}
  username: ${SMTP_USERNAME}
  password: ${SMTP_PASSWORD}
  from-email: ${FROM_EMAIL}
  to-emails: ${TO_EMAILS}

# Configuración de reportes para producción
report:
  channels: ${REPORT_CHANNELS:email,log}
  subject: ${REPORT_SUBJECT:Migration Report - API Example}

# Configuración de logging para producción
logging:
  level:
    com.jps.apiexample: INFO
    org.springframework: WARN
    org.springframework.mail: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/spring_boot_api_example.log
    max-size: 10MB
    max-history: 30
