# Configuración para entorno de desarrollo
spring:
  # Configuración de base de datos para desarrollo
  datasource:
    url: jdbc:${DB_TYPE:mysql}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:api_example_dev}
    username: ${DB_USERNAME:api_user}
    password: ${DB_PASSWORD:api_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # Configuración JPA para desarrollo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  
  # Configuración de Flyway para desarrollo
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
  
  # Configuración de mail para desarrollo (modo mock)
  mail:
    host: localhost
    port: 1025
    username: 
    password: 

# Configuración del servidor para desarrollo
server:
  port: 8083

# Configuración de la aplicación para desarrollo
app:
  host: localhost
  environment: development
  repository:
    type: ${APP_REPOSITORY_TYPE:mock}
    test-type: ${TEST_REPOSITORY_TYPE:mock}

# Configuración de email para desarrollo
email:
  smtp-host: localhost
  smtp-port: 1025
  username: 
  password: 
  from-email: dev@spring_boot_api_example.com
  to-emails: dev@spring_boot_api_example.com

# Configuración de reportes para desarrollo
report:
  channels: log
  subject: Migration Report - API Example (Development)

# Configuración de logging para desarrollo
logging:
  level:
    com.jps.apiexample: DEBUG
    org.springframework.web: DEBUG
    org.springframework.mail: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
