# Configuración principal de la aplicación
spring:
  application:
    name: spring_boot_api_example
  
  # Configuración de base de datos (solo si no es mock)
  datasource:
    url: jdbc:${DB_TYPE:mysql}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:api_example}
    username: ${DB_USERNAME:api_user}
    password: ${DB_PASSWORD:api_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # Configuración JPA/Hibernate (solo si no es mock)
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  
  # Configuración de Flyway para migraciones (solo si no es mock)
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  
  # Configuración del servidor
  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 32MB
  
  # Configuración de mail
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# Configuración del servidor
server:
  port: ${PORT:8080}

# Configuración de la aplicación
app:
  host: ${HOST:localhost}
  environment: ${APP_ENV:development}
  repository:
    type: ${APP_REPOSITORY_TYPE:mock}
    test-type: ${TEST_REPOSITORY_TYPE:mock}

# Configuración de email
email:
  smtp-host: ${SMTP_HOST:smtp.gmail.com}
  smtp-port: ${SMTP_PORT:587}
  username: ${SMTP_USERNAME:}
  password: ${SMTP_PASSWORD:}
  from-email: ${FROM_EMAIL:}
  to-emails: ${TO_EMAILS:admin@spring_boot_api_example.com,notifications@spring_boot_api_example.com}

# Configuración de reportes
report:
  channels: ${REPORT_CHANNELS:email,log}
  subject: ${REPORT_SUBJECT:Migration Report - API Example}

# Configuración de logging
logging:
  level:
    com.jps.apiexample: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Configuración de OpenAPI/Swagger
springdoc:
  api-docs:
    path: /api/v1/swagger.json
  swagger-ui:
    path: /api/v1/docs
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
